#时钟周期约束
create_clock -period 20.000 -name clk [get_ports clk]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN AA18 [get_ports {B[0]}]
set_property PACKAGE_PIN W17 [get_ports {B[1]}]
set_property PACKAGE_PIN V17 [get_ports {B[2]}]
set_property PACKAGE_PIN AB20 [get_ports {B[3]}]
set_property PACKAGE_PIN AA19 [get_ports {B[4]}]
set_property PACKAGE_PIN V19 [get_ports {B[5]}]
set_property PACKAGE_PIN V18 [get_ports {B[6]}]
set_property PACKAGE_PIN Y19 [get_ports {B[7]}]
set_property PACKAGE_PIN AB18 [get_ports {LED7S[0]}]
set_property PACKAGE_PIN U17 [get_ports {LED7S[1]}]
set_property PACKAGE_PIN U18 [get_ports {LED7S[2]}]
set_property PACKAGE_PIN P14 [get_ports {LED7S[3]}]
set_property PACKAGE_PIN R14 [get_ports {LED7S[4]}]
set_property PACKAGE_PIN R18 [get_ports {LED7S[5]}]
set_property PACKAGE_PIN T18 [get_ports {LED7S[6]}]
set_property PACKAGE_PIN P16 [get_ports {A[1]}]
set_property PACKAGE_PIN R17 [get_ports {A[2]}]
set_property PACKAGE_PIN N15 [get_ports {A[3]}]
set_property PACKAGE_PIN N14 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED7S[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED7S[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED7S[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED7S[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED7S[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED7S[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED7S[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
